CREATE TABLE logins (
  LoginId int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Email varchar(50) NOT NULL,
  LastLogin datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
